version: '3'

services:
 postgres:
  image: postgres
  restart: always
  container_name: plant-palace
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: b17i19
   POSTGRES_DB: plant-palace
  ports:
   - "5432:5432"
  networks:
   - plant-palace-network

 spring-boot-app:
  build:
   context: .
   dockerfile: Dockerfile
  environment:
   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/plant_palace
   SPRING_DATASOURCE_USERNAME: postgres
   SPRING_DATASOURCE_PASSWORD: b17i19
   SPRING_JPA_HIBERNATE_DDL_AUTO: update
   SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
   SPRING_JPA_SHOW_SQL: true
   SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  depends_on:
   - postgres
  ports:
   - "9090:9090"
  networks:
   - plant-palace-network
volumes:
 init:
networks:
 plant-palace-network:
  driver: bridge